# Generated by Django 5.1.1 on 2024-09-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userAuth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="user",
            name="profession",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
